name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2

      # Step 3: Set Git config (set user email and name)
      - name: Set Git identity
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"

      # Step 4: Install dependencies and build the React app
      - name: Install dependencies and build
        working-directory: UI
        run: npm install

      # Step 5: Run tests
#      - name: Run tests
#        run: |
#          cd UI
#          npm install

      # Step 5: Deploy to GitHub Pagess
      - name: Deploy to GitHub Pages
        working-directory: UI
        run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npm run deploy -- -u "github-actions-bot <support+actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
