name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "*"  # Trigger on push to the main branch
  pull_request:
    branches:
      - "*"  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2

      # Step 3: Set Git config (set user email and name)
      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 4: Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          cd UI
          npm install

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          cd UI
          if [ "${GITHUB_REF}" == 'refs/heads/main' ]; then
            npm run deploy
          else
            npm run deploy:test
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
