name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2

      # Step 3: Get Version
      - name: Get version from package.json
        id: package_version
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      # Step 4: Set Git config (set user email and name) and Create Version Tag
      - name: Set Git identity and Create Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag v${VERSION}
          git push -f https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git v${VERSION}

      # Step 5: Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          cd UI
          npm install

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          cd UI
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
