name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2

      # Step 3: Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          cd UI
          npm install

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          cd UI
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
