name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for better caching and cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t portfolio -f UI/Dockerfile .

      # Step 4: Copy the built files from the container
      - name: Extract build output from container
        run: |
          docker create --name extract-container portfolio
          docker cp extract-container:/ui/build ./build
          docker rm extract-container

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ui/build
          token: ${{ secrets.GH_TOKEN }}
